name: general

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  

  sea-action:
    name: Build SEA
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Find Node
        id: find-node
        run:
          echo "node=$(node -e 'console.log(process.argv[0]);')" >>
          $env:GITHUB_OUTPUT

      - name: SEA
        id: sea
        uses: bryopsida/node-sea-action@v1
        with:
          working-dir: .
          output-dir: build
          executable-name: sea
          sea-config-path: ./sea-config.json
          node-path: ${{ steps.find-node.outputs.node }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-sea
          path: build/
          if-no-files-found: error